import test from 'node:test';
import assert from 'node:assert/strict';
import { LocalRuntimeRepository, RuntimeError, decodeState, validateDraft, clone } from '../../.qa-domain/local-runtime.js';
import { demoScenarios } from '../../.qa-domain/scenarios.js';
function fixture() {
 let raw=null,index=0,notifications=0,deny=false;
 const storage={getItem:()=>raw,setItem:(_k,v)=>{if(deny)throw Error('QuotaExceeded');raw=v}};
 const repo=new LocalRuntimeRepository(storage,async job=>job(),()=>notifications++,()=> '2026-09-05T13:00:00.000Z',()=>`id-${String(++index).padStart(8,'0')}`);
 return {repo,get raw(){return raw},set raw(v){raw=v},deny:()=>deny=true,get notifications(){return notifications}};
}
function values(fields){return Object.fromEntries(fields.map(f=>[f.key,f.type==='select'?f.options[0]:f.type==='date'?'2026-09-10':'演示记录']))}
async function completeDraft(repo,scenario=demoScenarios[0]){let d=await repo.createDraft(scenario);d.data=values(scenario.requestFields);d.subjects=[values(scenario.subjectFields)];return repo.saveDraft(d)}
const errorCode=code=>e=>e instanceof RuntimeError&&e.code===code;
test('draft captures an independent scenario copy',async()=>{const{repo}=fixture();const scenario=clone(demoScenarios[0]);const d=await repo.createDraft(scenario);scenario.version='future';assert.notEqual(d.snapshot.version,scenario.version);d.data.customer='outside';assert.equal(repo.read().drafts[0].data.customer,undefined)});
test('initial draft reports required request, subject fields',async()=>{const{repo}=fixture();const d=await repo.createDraft(demoScenarios[0]);const issues=validateDraft(d);assert(issues.some(i=>i.step===1));assert(issues.some(i=>i.step===2))});
test('clearing selection remains zero and blocks submit',async()=>{const{repo}=fixture();let d=await completeDraft(repo);d.itemCodes=[];d=await repo.saveDraft(d);assert(validateDraft(d).some(i=>i.path==='items'));await assert.rejects(repo.submitDraft(d.id,d.revision),errorCode('VALIDATION_FAILED'));assert.equal(repo.read().requests.length,0)});
test('unknown item cannot enter the runtime snapshot',async()=>{const{repo}=fixture();let d=await completeDraft(repo);d.itemCodes=['UNREGISTERED'];d=await repo.saveDraft(d);await assert.rejects(repo.submitDraft(d.id,d.revision),errorCode('VALIDATION_FAILED'))});
test('submit is idempotent and creates only the first work item',async()=>{const{repo}=fixture();const d=await completeDraft(repo);const a=await repo.submitDraft(d.id,d.revision);const b=await repo.submitDraft(d.id,d.revision);assert.equal(a.id,b.id);assert.equal(repo.read().requests.length,1);assert.equal(repo.read().workItems.length,1);assert.equal(repo.read().workItems[0].nodeIndex,0)});
test('submitted draft cannot be overwritten',async()=>{const{repo}=fixture();const d=await completeDraft(repo);await repo.submitDraft(d.id,d.revision);await assert.rejects(repo.saveDraft({...d,data:{}}),errorCode('DRAFT_READONLY'))});
test('stale draft revision is rejected without losing the first write',async()=>{const{repo}=fixture();const d=await completeDraft(repo);const stale=clone(d);d.data.customer='first writer';await repo.saveDraft(d);stale.data.customer='second writer';await assert.rejects(repo.saveDraft(stale),errorCode('VERSION_CONFLICT'));assert.equal(repo.read().drafts[0].data.customer,'first writer')});
test('scenario version cannot be silently replaced in a draft',async()=>{const{repo}=fixture();const d=await completeDraft(repo);d.snapshot.version='9.0.0';await assert.rejects(repo.saveDraft(d),errorCode('SNAPSHOT_LOCKED'))});
test('invalid persisted JSON is preserved and never reset',async()=>{const f=fixture();f.raw='{broken';assert.throws(()=>f.repo.read(),errorCode('STORAGE_INVALID'));await assert.rejects(f.repo.createDraft(demoScenarios[0]),errorCode('STORAGE_INVALID'));assert.equal(f.raw,'{broken')});
test('incompatible storage version is rejected',()=>assert.throws(()=>decodeState(JSON.stringify({schemaVersion:99})),errorCode('STORAGE_INVALID')));
test('failed storage write neither notifies nor commits',async()=>{const f=fixture();const d=await completeDraft(f.repo);const before=f.raw;const count=f.notifications;f.deny();d.data.customer='unsaved';await assert.rejects(f.repo.saveDraft(d),errorCode('STORAGE_WRITE_FAILED'));assert.equal(f.raw,before);assert.equal(f.notifications,count)});
test('node cannot complete before it has started',async()=>{const{repo}=fixture();const d=await completeDraft(repo);await repo.submitDraft(d.id,d.revision);const w=repo.read().workItems[0];await assert.rejects(repo.saveWork(w.id,w.revision,{},false,true),errorCode('WORK_READONLY'))});
test('required node fields block completion',async()=>{const{repo}=fixture();const d=await completeDraft(repo);await repo.submitDraft(d.id,d.revision);let w=repo.read().workItems[0];w=await repo.startWork(w.id,w.revision);await assert.rejects(repo.saveWork(w.id,w.revision,{},false,true),errorCode('VALIDATION_FAILED'));assert.equal(repo.read().workItems.length,1)});
test('node completion is idempotent and completed evidence is read-only',async()=>{const{repo}=fixture();const d=await completeDraft(repo);await repo.submitDraft(d.id,d.revision);let w=repo.read().workItems[0];w=await repo.startWork(w.id,w.revision);const record=values(d.snapshot.nodes[0].fields);await repo.saveWork(w.id,w.revision,record,true,true);await repo.saveWork(w.id,w.revision,record,true,true);assert.equal(repo.read().workItems.length,2);await assert.rejects(repo.saveWork(w.id,w.revision,{},true),errorCode('WORK_READONLY'))});
test('stale work item write is rejected',async()=>{const{repo}=fixture();const d=await completeDraft(repo);await repo.submitDraft(d.id,d.revision);let w=repo.read().workItems[0];w=await repo.startWork(w.id,w.revision);await repo.saveWork(w.id,w.revision,{notes:'first'},false);await assert.rejects(repo.saveWork(w.id,w.revision,{notes:'stale'},false),errorCode('VERSION_CONFLICT'))});
test('all three scene sequences complete without changing their snapshots',async()=>{for(const scenario of demoScenarios){const{repo}=fixture();const d=await completeDraft(repo,scenario);const r=await repo.submitDraft(d.id,d.revision);for(let i=0;i<scenario.nodes.length;i++){let w=repo.read().workItems.find(w=>w.nodeIndex===i);assert(w);w=await repo.startWork(w.id,w.revision);const n=scenario.nodes[i];if(n.requiresConfirmation)await assert.rejects(repo.saveWork(w.id,w.revision,values(n.fields),false,true),errorCode('CONFIRMATION_REQUIRED'));await repo.saveWork(w.id,w.revision,values(n.fields),true,true)}const s=repo.read();assert.equal(s.requests[0].status,'COMPLETED');assert.equal(s.workItems.length,scenario.nodes.length);assert(s.workItems.every(w=>w.status==='COMPLETED'));assert.deepEqual(s.requests[0].snapshot,r.snapshot)}});
test('date validation rejects impossible calendar dates',async()=>{const{repo}=fixture();const d=await completeDraft(repo);d.data.dueDate='2026-02-31';assert(validateDraft(d).some(i=>i.path==='request.dueDate'))});
test('unregistered renderer and inactive scene cannot initialize a request',async()=>{const{repo}=fixture();const s=clone(demoScenarios[0]);s.nodes[0].renderer='https://untrusted.invalid/ui.js';await assert.rejects(repo.createDraft(s),errorCode('SCENARIO_UNAVAILABLE'));s.nodes=demoScenarios[0].nodes;s.active=false;await assert.rejects(repo.createDraft(s),errorCode('SCENARIO_UNAVAILABLE'))});
